version: 1.9.6

sources:
  - name: schedule
    database: gtfs_test
    schema: schedule
    tables:
      - name: calendar_dates
      - name: calendar
      - name: routes
      - name: stop_times
      - name: stops
      - name: trips
  - name: trip_updates
    database: gtfs_test
    schema: trip_updates
    tables:
      - name: trip_updates
